/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_yah_tests_perceptron_jni_NativeNeuralNetwork */

#ifndef _Included_org_yah_tests_perceptron_jni_NativeNeuralNetwork
#define _Included_org_yah_tests_perceptron_jni_NativeNeuralNetwork
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_yah_tests_perceptron_jni_NativeNeuralNetwork
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_yah_tests_perceptron_jni_NativeNeuralNetwork_delete
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_yah_tests_perceptron_jni_NativeNeuralNetwork
 * Method:    create
 * Signature: ([I)J
 */
JNIEXPORT jlong JNICALL Java_org_yah_tests_perceptron_jni_NativeNeuralNetwork_create
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     org_yah_tests_perceptron_jni_NativeNeuralNetwork
 * Method:    layers
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_yah_tests_perceptron_jni_NativeNeuralNetwork_layers
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_yah_tests_perceptron_jni_NativeNeuralNetwork
 * Method:    features
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_yah_tests_perceptron_jni_NativeNeuralNetwork_features__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_yah_tests_perceptron_jni_NativeNeuralNetwork
 * Method:    outputs
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_yah_tests_perceptron_jni_NativeNeuralNetwork_outputs
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_yah_tests_perceptron_jni_NativeNeuralNetwork
 * Method:    features
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_yah_tests_perceptron_jni_NativeNeuralNetwork_features__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_yah_tests_perceptron_jni_NativeNeuralNetwork
 * Method:    neurons
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_yah_tests_perceptron_jni_NativeNeuralNetwork_neurons
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_yah_tests_perceptron_jni_NativeNeuralNetwork
 * Method:    propagate
 * Signature: (JJLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_yah_tests_perceptron_jni_NativeNeuralNetwork_propagate
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     org_yah_tests_perceptron_jni_NativeNeuralNetwork
 * Method:    evaluate
 * Signature: (JJLjava/nio/IntBuffer;)D
 */
JNIEXPORT jdouble JNICALL Java_org_yah_tests_perceptron_jni_NativeNeuralNetwork_evaluate
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     org_yah_tests_perceptron_jni_NativeNeuralNetwork
 * Method:    train
 * Signature: (JJD)V
 */
JNIEXPORT void JNICALL Java_org_yah_tests_perceptron_jni_NativeNeuralNetwork_train
  (JNIEnv *, jclass, jlong, jlong, jdouble);

/*
 * Class:     org_yah_tests_perceptron_jni_NativeNeuralNetwork
 * Method:    seed
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_yah_tests_perceptron_jni_NativeNeuralNetwork_seed
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
